TOPDIR = ../../../
include $(DWMAKE)/makedefs

CXXFILES = bootstrap.cpp

LINKER_ARGS = -L$(TOPDIR)/lib/$(OSARCH)/

LIBS =  -losgDB -losgCompass -losgText -losgUtil

EXEC = bootstrap

include $(DWMAKE)/makerules
