TOPDIR = ../
include $(DWMAKE)/makedefs

SUBDIRS = \
    MakeMoonImages\
    MakeSunImage\
    osgEphemerisLib\
    osgEphemerisPlugin\
    Gui\
    CallbackExample\

#    Viewer\


include $(DWMAKE)/makerules

