TOPDIR = ../../
include $(DWMAKE)/makedefs

CXXFILES = main.cpp\

MOON_IMAGES = \
        moon_1024x512.jpg\
        moon_normal_1024x512.jpg\

LIBS =  -losgDB -losg  -lProducer


EXEC = makeMoonImages

include $(DWMAKE)/makerules

