#!/bin/sh

VERSION=`date +"%Y%m%d%H%M%S"`
TARBALL_NAME=osgEphemeris-"$VERSION".tar.gz
TARBALL_DIR=osgEphemeris-"$VERSION"

rm -rf $TARBALL_DIR
mkdir $TARBALL_DIR
/usr/bin/cvs -Q -d /cvs/osg export -D now -d $TARBALL_DIR osgEphemeris

tar cvf - $TARBALL_DIR | gzip > $TARBALL_NAME

rm -rf $TARBALL_DIR
mv $TARBALL_NAME Download/Generated

exit 0

